theme: jekyll-theme-minimal
lang: "es"
title: Daniupina
author: Daniela Risaro
email: dbrisaro@gmail.com

# Navigation Menus
header_navigation:
  - title: Documentation
    url: /docs/

  - title: About
    url: /about/

  - title: Blog
    url: /archive/

  - title: Contact
    url: mailto:you@example.com

footer_navigation:
  - title: privacy
    url: /privacy/

  - title: terms
    url: /terms/
